# Generated by Django 4.0.6 on 2022-07-11 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenticateuser', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
